# Generated by Django 4.1.3 on 2022-12-07 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fonds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Назва фонду')),
                ('desc', models.TextField(verbose_name='Опис')),
                ('url_global', models.CharField(max_length=1000, unique=True, verbose_name='URL-посилання')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
            ],
            options={
                'verbose_name': 'Фонд',
                'verbose_name_plural': 'Фонди',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Назва')),
                ('desc', models.CharField(blank=True, max_length=255, verbose_name='Опис')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото секції')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='SLUG')),
            ],
            options={
                'verbose_name': 'Розділ',
                'verbose_name_plural': 'Розділи',
            },
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(verbose_name='Цитата')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fonds.section')),
            ],
            options={
                'verbose_name': 'Цитата',
                'verbose_name_plural': 'Цитати',
            },
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('my_order', models.PositiveIntegerField(default=0)),
                ('fond_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fonds.fonds')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
                'ordering': ['my_order'],
            },
        ),
        migrations.AddField(
            model_name='fonds',
            name='section_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fonds.section', verbose_name='Розділ'),
        ),
    ]
